# Generated by Django 4.2.3 on 2023-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.DateTimeField()),
                ('last_name', models.DateTimeField()),
                ('course', models.TextField()),
                ('hasScholarship', models.BooleanField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.DateTimeField()),
                ('last_name', models.DateTimeField()),
                ('qualification', models.TextField()),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
