# Generated by Django 4.2.3 on 2023-07-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
