# Generated by Django 4.2.3 on 2023-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_fist_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.TextField(),
        ),
    ]
