# Generated by Django 4.2.3 on 2023-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
